.. Links and substitutions that might be shared across pages
.. vim: ft=rst

.. Documentation
.. _sphinx: http://sphinx-doc.org
.. _restructuredtext: http://docutils.sourceforge.net/rst.html
.. _ghp-import: https://pypi.python.org/pypi/ghp-import

.. Python and common libraries
.. _python: https://www.python.org
.. _python.org releases: https://www.python.org/download/releases
.. _distutils: http://docs.python.org/2/library/distutils.html
.. _setuptools: http://pypi.python.org/pypi/setuptools
.. _distribute: http://pypi.python.org/pypi/distribute
.. _pip: http://pypi.python.org/pypi/pip
.. _easy_install: https://pythonhosted.org/setuptools/easy_install.html
.. _wheels: https://pypi.python.org/pypi/wheel
.. _numpy: http://www.numpy.org
.. _matplotlib: http://matplotlib.org/
.. _scipy: https://www.scipy.org
.. _nose: http://readthedocs.org/docs/nose/en/latest
.. _nose-ipdb: https://github.com/flavioamieiro/nose-ipdb
.. _ipython: http://ipython.org

.. Windows development
.. _mingw: http://mingw.org
.. _msys: http://www.mingw.org/wiki/MSYS
.. _mingw-w64: http://mingw-w64.org
.. _powershell: http://www.microsoft.com/powershell
.. _msysgit: http://code.google.com/p/msysgit
.. _putty: http://www.chiark.greenend.org.uk/~sgtatham/putty

.. Compilers, libraries
.. _GNU compiler collection:
   https://en.wikipedia.org/wiki/GNU_Compiler_Collection>`_
.. _MS runtime libraries:
   https://en.wikipedia.org/wiki/Microsoft_Windows_library_files#Runtime_libraries
.. _table of MSVC versions and CRTs:
   https://matthew-brett.github.io/pydagogue/python_msvc.html#visual-studio-compiler-versions
.. _glibc: https://www.gnu.org/software/libc

.. Licenses
.. _CC0 license: http://creativecommons.org/publicdomain/zero/1.0/legalcode

.. This repo
.. _mingwpy pages issue : https://github.com/mingwpy/mingwpy.github.io/issues

.. Substitutions
.. |emdash| unicode:: U+02014
.. |--| unicode:: U+2013   .. en dash
.. |---| unicode:: U+2014  .. em dash, trimming surrounding whitespace
   :trim:

