.. Links and substitutions that might be shared across pages
.. vim: ft=rst

.. Mingw etc
.. _mingw-w64 history:
   http://sourceforge.net/p/mingw-w64/wiki2/History
.. _mingw-w64 source releases:
   http://sourceforge.net/projects/mingw-w64/files/mingw-w64/mingw-w64-release/
.. _mingw wikipedia page: https://en.wikipedia.org/wiki/MinGW
.. _mingw-w64 wikipedia section: https://en.wikipedia.org/wiki/MinGW#MinGW-w64
.. _mingw-builds: https://github.com/niXman/mingw-builds
.. _msys2: http://sourceforge.net/projects/msys2/
.. _mingw-w64 exception handling:
   http://sourceforge.net/p/mingw-w64/wiki2/Exception%20Handling/
.. _SO post on mingw-w64 exception handling:
   http://stackoverflow.com/questions/15670169/what-is-difference-between-sjlj-vs-dwarf-vs-seh
.. _mingwpy bitbucket repo:
   https://bitbucket.org/carlkl/mingw-w64-for-python/downloads
.. _mingwpy anaconda site: https://anaconda.org/carlkl/mingwpy

.. BLAS / LAPACK
.. _BLAS: http://www.netlib.org/blas/
.. _LAPACK: http://www.netlib.org/lapack/
.. _ATLAS: http://math-atlas.sourceforge.net
.. _Intel MKL:
.. _MKL: https://software.intel.com/en-us/intel-mkl
.. _MKL wikipedia entry: https://en.wikipedia.org/wiki/Math_Kernel_Library
.. _OpenBLAS: http://www.openblas.net
.. _OpenBLAS on github: https://github.com/xianyi/OpenBLAS
.. _CBLAS: http://www.netlib.org/blas/#_cblas
.. _AMD core math library:
.. _ACML:
   http://developer.amd.com/tools-and-sdks/cpu-development/amd-core-math-library-acml
.. _AMD compute libraries:
.. _ACL:
   http://developer.amd.com/tools-and-sdks/opencl-zone/acl-amd-compute-libraries/
.. _BLIS: https://github.com/flame/blis
.. _libflame: https://github.com/flame/libflame
.. _netlib BLAS: http://www.netlib.org/blas
.. _netlib LAPACK: http://www.netlib.org/lapack/index.html
.. _GotoBLAS2:
   https://www.tacc.utexas.edu/research-development/tacc-software/gotoblas2
.. _BLAS LAPACK review:
   http://www.wittwer.nl/wp-content/uploads/2009/08/blas_lapack.pdf
.. _Eigen: http://eigen.tuxfamily.org/index.php?title=Main_Page

.. Windows
.. _PE format:
.. _Portable executable format:
.. _Portable executable:
.. _PE: https://en.wikipedia.org/wiki/Portable_Executable
.. _Structured exception handling:
.. _SEH: https://www.microsoft.com/msj/0197/exception/exception.aspx
.. _Windows DLL notes: https://github.com/numpy/numpy/wiki/windows-dll-notes
.. _Windows versions: https://github.com/numpy/numpy/wiki/Windows-versions

.. Documentation
.. _sphinx: http://sphinx-doc.org
.. _restructuredtext: http://docutils.sourceforge.net/rst.html
.. _ghp-import: https://pypi.python.org/pypi/ghp-import

.. Related pages
.. _numerical software on Windows:
   https://github.com/numpy/numpy/wiki/Numerical-software-on-Windows
.. _fortran on Windows:
   https://github.com/numpy/numpy/wiki/Numerical-software-on-Windows#fortran

.. Python and common libraries
.. _python: https://www.python.org
.. _python.org releases: https://www.python.org/download/releases
.. _distutils: http://docs.python.org/2/library/distutils.html
.. _setuptools: http://pypi.python.org/pypi/setuptools
.. _distribute: http://pypi.python.org/pypi/distribute
.. _pip: http://pypi.python.org/pypi/pip
.. _easy_install: https://pythonhosted.org/setuptools/easy_install.html
.. _wheel:
.. _wheels: https://pypi.python.org/pypi/wheel
.. _numpy: http://www.numpy.org
.. _matplotlib: http://matplotlib.org/
.. _scipy: https://www.scipy.org
.. _nose: http://readthedocs.org/docs/nose/en/latest
.. _nose-ipdb: https://github.com/flavioamieiro/nose-ipdb
.. _ipython: http://ipython.org

.. Windows development
.. _mingw: http://mingw.org
.. _msys: http://www.mingw.org/wiki/MSYS
.. _mingw-w64: http://mingw-w64.org
.. _powershell: http://www.microsoft.com/powershell
.. _msysgit: http://code.google.com/p/msysgit
.. _putty: http://www.chiark.greenend.org.uk/~sgtatham/putty

.. Compilers, libraries
.. _GNU compiler collection:
   https://en.wikipedia.org/wiki/GNU_Compiler_Collection
.. _MS runtime libraries:
   https://en.wikipedia.org/wiki/Microsoft_Windows_library_files#Runtime_libraries
.. _table of MSVC versions and CRTs:
   https://matthew-brett.github.io/pydagogue/python_msvc.html#visual-studio-compiler-versions
.. _glibc: https://www.gnu.org/software/libc
.. _binutils: http://www.gnu.org/software/binutils
.. _binutils wikipedia page: https://en.wikipedia.org/wiki/GNU_Binutils

.. Languages
.. _Julia: http://julialang.org

.. Licenses
.. _CC0 license: http://creativecommons.org/publicdomain/zero/1.0/legalcode

.. This repo
.. _mingwpy pages issue : https://github.com/mingwpy/mingwpy.github.io/issues

.. Substitutions
.. |emdash| unicode:: U+02014
.. |--| unicode:: U+2013   .. en dash
.. |---| unicode:: U+2014  .. em dash, trimming surrounding whitespace
   :trim:

